### ISSUE TITLE
Error: Cannot find the specified file

### ISSUE THREAD

**Issue by HendrikKoelbel** [mrward/monodevelop-task-runner-addin#11]
I always get this error message when running Gulp and Grant files.
But with NPM it works.

> Failed to load /Users/xxxxxx/Developer/Projects/xxxxxx/xxxxxx/gulpfile.js
ApplicationName='gulp', CommandLine='--tasks-simple', CurrentDirectory='/Users/xxxxxx/Developer/Projects/xxxxxx/xxxxxx', Native error= Cannot find the specified file

![image](https://user-images.githubusercontent.com/31684940/82291087-9addbd00-99a8-11ea-8146-8861dafea83b.png)

VS Mac Version: 8.5.6 (build 11)
Task Runner Explorer Version: https://addins.monodevelop.com/Project/Index/374 (latest beta version)
Task Runner Bundle Version: https://addins.monodevelop.com/Project/Index/375 (latest beta version)

Is this error known? 
How else can I run gulp or grunt files in my ASP.NET Web site?

**Comment by mrward** [comment]
The error looks like VS Mac cannot find gulp. VS Mac has a different PATH compared with the Terminal so it cannot always find applications if they are not on the set of paths it knows about.

One workaround would be to start VS Mac from the terminal:

    open -n "/Applications/Visual Studio.app"

Another workaround would be to create a symlink to gulp in one of the directories that VS Mac has on its PATH such as `/usr/local/bin`

Another workaround would be to amend the PATH environment variable for all GUI apps using a startup daemon - https://lastexitcode.com/blog/2020/04/11/ManageGlobalNuGetFoldersForVisualStudioMac/

I think creating a symlink would be the simplest approach here. But probably worth testing if starting VS Mac from the command line solves the problem for you first - I am assuming that you can run the gulp tasks from the terminal.

**Comment by HendrikKoelbel** [comment]
I have added "/usr/local/bin" to my .zshrc/.bash_profiles.
Now at least it doesn't seem to show an error anymore.
I will test it in the near future and give a feedback. 

Thank you for your answer, I didn't find anything in the internet. :)
